export const leadershipTeam = [
  {
    key: 1,
    name: "Jim Anderson",
    title: "CTO & Co-Founder",
    avatar: "/images/team/Jim.png",
    description: [
      "Over 20 years of expertise in protecting identity and data.",
      "Advised US government and law enforcement on counter-terrorism and security.",
      "Developed tech solutions for U.S. Patriot Act, KYC, and AML compliance.",
      "Pioneer in IP and data security.",
      "Co-founded About.com (Acquired).",
      "Led US Platform at Spotify (2011-2014): Contributed to launch and growth.",
      "Inventor & author of 25+ U.S. patents in security, AI/ML, telecommunications, and mobile solutions.",
    ],
    companies: ["/images/companies/10.svg", "/images/companies/5.svg"],
  },
  {
    key: 2,
    name: "Steven G Chrust",
    title: "Co-Founder & Vice Chairman ",
    avatar: "/images/team/SGC.png",
    description: [
      "Helped merge Winstar Communications into a $10bn enterprise.",
      "Led Worlds, Inc's 3D virtual community platform (1999-2000).",
      "Founded Centripetal Capital Partners, focusing on private equity growth.",
      "Provides leadership and governance to growth-stage companies.",
      "Lectured at Harvard and testified on AT&T's break-up.",
      "Expert in telecommunications policy and industry trends.",
      "Experience scaling and leading high-growth companies.",
    ],
    companies: ["/images/companies/11.svg", "/images/companies/6.svg"],
  },
];

export const teamMembers = [
  {
    key: 1,
    name: "Laura Trumbull",
    title: "COO",
    bio: "Served as CTO at American Real-Time Services, COO/CTO at Chaikin Analytics, and VP of Marketing App Tech at Meredith.",
    imageUrl: "/images/team/laura_trumbull.png",
  },
  {
    key: 2,
    name: "Tom Saleh",
    title: "CIO",
    bio: "Founder/CEO of XNET (acquired) and CTO at the Financial Accounting Standards Board.",
    imageUrl: "/images/team/tom_saleh.png",
  },
  {
    key: 3,
    name: "Stephen Rossetter",
    title: "CFO",
    bio: "Co-Founder/Managing Partner at Centripetal Capital Partners.",
    imageUrl: "/images/team/stephen_rossetter.png",
  },
  {
    key: 4,
    name: "Larry Rafsky, PhD",
    title: "Head of Data Science",
    bio: "Founder/CEO of Acquire Media (acquired) and IDD at Dow Jones.",
    imageUrl: "/images/team/larry_rafsky.png.png",
  },
  {
    key: 5,
    name: "Jeffrey Brodlieb",
    title: "Business Strategy",
    bio: "VP of Finance & Ops at GE Capital and Principal at Boston Consulting Group.",
    imageUrl: "/images/team/jeffrey_brodlieb.png.png",
  },
];

export const advisorMember = [
  {
    key: 1,
    name: "David Bell",
    title: "Chairman Emeritus & Senior Advisor",
    avatar: "/images/team/david_bell.png",
    description: [
      "Senior Advisor @ Google (2006-2009) & AOL/Oath.",
      "Advertising Hall of Fame Inductee (2007).",
      "Chairman Emeritus & CEO @ Interpublic Group (NYSE: IPG).",
      "CEO @ True North Communications (NASDAQ: TNO): Led its $2.1 billion acquisition by IPG.",
      "CEO @ Bozell Worldwide.",
      "Founder & Chairman @ Gyro.",
    ],
    companies: ["/images/companies/4.svg", "/images/companies/13.svg"],
  },
  {
    key: 2,
    name: "Lawrence Leibowitz",
    title: "COO & Financial Markets Leader",
    avatar: "/images/team/lawrence_leibowitz.png",
    description: [
      "COO & Head of Equity Markets @ NYSE Euronext (NYSE: NYX): Played a significant role during its $10.2 billion acquisition by Intercontinental Exchange (ICE) in 2013.",
      "MD & COO @ UBS Americas Equities.",
      "Board Member of Crux Informatics, Cowen Inc., and Enfusion Systems.",
      "Vice-Chairman of Xpansiv Markets.",
    ],
    companies: ["/images/companies/13.svg", "/images/companies/16.svg"],
  },
  {
    key: 3,
    name: "Keith Turco",
    title: "Growth & Marketing Innovator",
    avatar: "/images/team/keith_turco.png",
    description: [
      "Board Member @ American Advertising Federation.",
      "CEO @ Madison Logic.",
      "Chief Growth Officer @ MERGE.",
      "Chief Commercial Officer & President, Americas @ Digimarc (Nasdaq: DMRC).",
      "EVP, Worldwide Managing Director @ Ogilvy.",
      "President @ gyro NY: Acquired by Dentsu (Euronext: DNTUY).",
    ],
    companies: ["/images/companies/11.svg", "/images/companies/18.svg"],
  },
  {
    key: 4,
    name: "Andrew O’Doherty",
    title: "Blockchain & Digital Transformation Expert",
    avatar: "/images/team/andrew_odoherty.png",
    description: [
      "Founder/Managing Partner @ gm3: A Business & Technology Advisory firm.",
      "Founder @ My Data Hub: An early-stage decentralized data marketplace platform leveraging blockchain technology.",
      "Global Head of Onboarding Ops & Digital Transformation @ Citigroup Securities Services (NYSE: C).",
    ],
    companies: ["/images/companies/1.svg", "/images/companies/17.svg"],
  },
];
