export const leadershipTeam = [
  {
    key: 1,
    name: "Jim Anderson",
    title: "CTO & Co-Founder",
    avatar: "/images/team/Jim.png",
    description: [
      "Co-founded About.com (Acquired).",
      "Led US Platform at Spotify (2011-2014): Employee #6",
      "Over 20 years of expertise in protecting identity and data.",
      "Advised US government and law enforcement on counter-terrorism and security.",
      "Developed tech solutions for U.S. Patriot Act, KYC, and AML compliance.",
      "Pioneer in IP and data security.",
      "Inventor & author of 25+ U.S. patents in security, AI/ML, telecommunications, and mobile solutions.",
    ],
    companies: ["/images/companies/10.svg", "/images/companies/5.svg"],
    linkedinUrl: "https://www.linkedin.com/in/jimcto",
  },
  {
    key: 2,
    name: "Steven G Chrust",
    title: "Executive Vice Chairman & Co-Founder",
    avatar: "/images/team/SGC.png",
    description: [
      "Co-Founder of Winstar Communications (Nasdaq: WCII), which merged into a $10bn enterprise.",
      "Chairman at Worlds Inc (Nasdaq: WDDD), a 3D virtual community platform (1999-2000).",
      "Senior Principal at Centripetal Capital Partners, focusing on private equity growth.",
      "Chairman at several growth-stage companies.",
      "Expert in telecommunications policy and industry trends.",
      "Experience scaling and leading high-growth companies.",
      "Lectured at Harvard Business School and testified before Congress on AT&T's break-up.",
    ],
    companies: ["/images/companies/19.svg", "/images/companies/6.svg"],
    linkedinUrl: "https://www.linkedin.com/in/schrust",
  },
];

export const advisorMember = [
  {
    key: 1,
    name: "David Bell",
    title: "Chairman Emeritus & Senior Advisor",
    avatar: "/images/team/david_bell.png",
    description: [
      "Senior Advisor @ Google (2006-2009) & AOL/Oath.",
      "Advertising Hall of Fame Inductee (2007).",
      "Chairman Emeritus & CEO @ Interpublic Group (NYSE: IPG).",
      "CEO @ True North Communications (NASDAQ: TNO): Led its $2.1 billion acquisition by IPG.",
      "CEO @ Bozell Worldwide.",
      "Founder & Chairman @ Gyro.",
    ],
    companies: ["/images/companies/4.svg", "/images/companies/12.svg"],
    linkedinUrl: "https://www.linkedin.com/in/david-bell-01276a5",
  },
  {
    key: 2,
    name: "Lawrence Leibowitz",
    title: "Senior Operating & Markets Leader",
    avatar: "/images/team/lawrence_leibowitz.png",
    description: [
      "COO & Head of Equity Markets @ NYSE Euronext (NYSE: NYX): Played a significant role during its $10.2 billion acquisition by Intercontinental Exchange (ICE) in 2013.",
      "MD & COO @ UBS Americas Equities.",
      "Board Member of Crux Informatics, Cowen Inc., and Enfusion Systems.",
      "Vice-Chairman of Xpansiv Markets.",
    ],
    companies: ["/images/companies/13.svg", "/images/companies/16.svg"],
    linkedinUrl: "https://www.linkedin.com/in/lleibowitz",
  },
  {
    key: 3,
    name: "Keith Turco",
    title: "Growth and Marketing Leader",
    avatar: "/images/team/keith_turco.png",
    description: [
      "Board Member @ American Advertising Federation.",
      "CEO @ Madison Logic.",
      "Chief Growth Officer @ MERGE.",
      "Chief Commercial Officer & President, Americas @ Digimarc (Nasdaq: DMRC).",
      "EVP, Worldwide Managing Director @ Ogilvy.",
      "President @ gyro NY: Acquired by Dentsu (Euronext: DNTUY).",
    ],
    companies: ["/images/companies/11.svg", "/images/companies/18.svg"],
    linkedinUrl: "https://www.linkedin.com/in/keith-turco",
  },
  {
    key: 4,
    name: "Andrew O’Doherty",
    title: "Capital & Digital Transformation Expert",
    avatar: "/images/team/andrew_odoherty.png",
    description: [
      "Founder/Managing Partner @ gm3: A Business & Technology Advisory firm.",
      "Founder @ My Data Hub: An early-stage decentralized data marketplace platform leveraging blockchain technology.",
      "Global Head of Ops & Onboarding Digital Transformation @ Citigroup Securities Services (NYSE: C).",
    ],
    companies: ["/images/companies/1.svg", "/images/companies/20.svg"],
    linkedinUrl: "https://www.linkedin.com/in/andrewirl",
  },
];

export const teamMembers = [
  {
    key: 1,
    name: "Andrew O’Doherty",
    title: "Chief Revenue Officer",
    avatar: "/images/team/andrew_odoherty.png",
    description: [
      "Managing Partner @ gm3.",
      "Founder @ My Data Hub.",
      "Global Head of Ops & Digital Transformation @ Citi Securities Services (NYSE: C).",
    ],
    companies: ["/images/companies/1.svg", "/images/companies/20.svg"],
    linkedinUrl: "https://www.linkedin.com/in/andrewirl",
  },
  {
    key: 2,
    name: "Laura Trumbull",
    title: "Chief Operating Officer",
    avatar: "/images/team/laura_trumbull.png",
    description: [
      "Served as CTO at American Real-Time Services.",
      "COO/CTO at Chaikin Analytics.",
      "VP of Marketing App Tech at Meredith.",
    ],
    companies: ["/images/companies/3.svg", "/images/companies/9.svg"],
    linkedinUrl: "https://www.linkedin.com/in/lauractrumbull",
  },
  {
    key: 3,
    name: "Tom Saleh",
    title: "Chief Information Officer",
    bio: "Founder/CEO of XNET (acquired) and CTO at the Financial Accounting Standards Board.",
    avatar: "/images/team/tom_saleh.png",
    description: [
      "Founder/CEO of XNET (acquired).",
      "CTO at the Financial Accounting Standards Board.",
    ],
    companies: ["/images/companies/7.svg", "/images/companies/13.svg"],
    linkedinUrl: "https://www.linkedin.com/in/tom-saleh-5a56b03",
  },
  {
    key: 4,
    name: "Stephen Rossetter",
    title: "Chief Financial Officer",
    avatar: "/images/team/stephen_rossetter.png",
    description: [
      "Co-Founder/Managing Partner at Centripetal Capital Partners.",
    ],
    companies: ["/images/companies/21.svg", "/images/companies/19.svg"],
    linkedinUrl: "https://www.linkedin.com/in/steve-rossetter-a81a08a",
  },
  {
    key: 5,
    name: "Larry Rafsky, PhD",
    title: "Head of Data Science, Machine Learning & Statistical Analysis",
    avatar: "/images/team/larry_rafsky.png",
    description: [
      "Founder/CEO of Acquire Media (acquired).",
      "IDD at Dow Jones.",
    ],
    companies: ["/images/companies/8.svg", "/images/companies/15.svg"],
    linkedinUrl: "https://www.linkedin.com/in/rafsky",
  },
  {
    key: 6,
    name: "Jeffrey Brodlieb",
    title: "Business Strategy",
    avatar: "/images/team/jeffrey_brodlieb.png",
    description: [
      "VP of Finance & Ops at GE Capital.",
      "Principal at Boston Consulting Group.",
    ],
    companies: ["/images/companies/2.svg", "/images/companies/23.svg"],
    linkedinUrl: "https://www.linkedin.com/in/jeff-brodlieb-07b18441",
  },
];
